### ISSUE TITLE
Love the idea, any demo videos showing the actual use of the app?

### ISSUE THREAD

**Issue by Orenoid** [minki-j/ai-mock-coding-interview-agent#29]
I've been looking for tools for mock coding interviews. I tried the app, couldn't login.  
The demo video linked in the readme looks more like a presentation, still no idea how the mock interview  works within the app.  A video showing an complete mock coding interview process would be appreciated.

**Comment by Orenoid** [comment]
Never mind, somehow I just managed to login, no idea what was wrong previously...
I'll close the issue and try the app first. But still, I think a demo video demonstrating the complete mock interview process would be great.

**Comment by minki-j** [comment]
@Orenoid Thanks for having interest on our project! Let us know how you find it and feel free to suggest any improvements.

We'll add a demo video soon. Thanks for the idea :)

**Comment by Orenoid** [comment]
> @Orenoid Thanks for having interest on our project! Let us know how you find it and feel free to suggest any improvements.
> 
> We'll add a demo video soon. Thanks for the idea :)

Sorry, I didn't see your comment and didn't receive notifications for it. If I remember correctly, I just searched something like "mock coding interview" on GitHub and this project was listed in the result.
